### ISSUE TITLE
data binding error

### ISSUE THREAD

**Issue by Virgilio123** [palmtreephp/form#8]
I updated the package and I'm testing the data binding function but I'm getting this error?
To retrieve data, I use the library Respect\Relational 
The data is correctly extracted into stdClass

Tank
```
$dati = \Flight::get("Mapper")->funzionari($id)->fetch();
$builder = new FormBuilder([], $dati);
$builder->add('nome', 'text', ['label'=>'Nome'])
    ->add('telefono', 'text', ['label' => 'Telefono'])
    ->add('profilo', 'choice', [
        'choices' => [
            'Dottrs' => 'DT',
            'INF'   => 'IF',
        ],
        'label'=>'Funzione Svolta',
    ]);
    $builder->add('Salvataggio', 'submit');
    $form = $builder->getForm();`
```
**Error**
````
Palmtree\Form\Form::getKey(): Return value must be of type string, null returned (0)
#0 D:\Sviluppo PHP\app\vendor\palmtree\form\src\FormRenderer.php(98): Palmtree\Form\Form->getKey()
#1 D:\Sviluppo PHP\app\vendor\palmtree\form\src\FormRenderer.php(40): Palmtree\Form\FormRenderer->buildElement()
#2 D:\Sviluppo PHP\app\vendor\palmtree\form\src\Form.php(82): Palmtree\Form\FormRenderer->render()
#3 D:\Sviluppo PHP\app\vendor\palmtree\form\src\Form.php(405): Palmtree\Form\Form->render()`
```

**Comment by andyexeter** [comment]
It looks like you're passing an empty array as the first argument to the form builder.

The first argument must be either the unique form key or an array of arguments, e.g.:

```php
new FormBuilder('my_form', $dati);
```

I'll update the documentation examples to include this!

**Comment by Virgilio123** [comment]
Thanks, It works perfect!
